language: erlang

env:
  - LUA="th"

branches:
  only:
    - master

install:
  - echo "==== Installing gfortran ===="
  - sudo apt-get install gfortran
  - echo "==== Installing hdf5 ===="
  - sudo apt-get install libhdf5-serial-dev hdf5-tools
  - echo "==== Installing dependencies ===="
  - curl -skL https://raw.github.com/torch/ezinstall/master/install-deps | sudo bash
  - echo "==== Installing Torch ===="
  - curl -skL https://raw.github.com/torch/ezinstall/master/install-luajit+torch | sudo bash
  - echo "==== Building torch-hdf5, using luarocks ===="
  - sudo /usr/local/bin/luarocks make

script: 'for x in tests/test*.lua ; do echo "==== $x ====" ; th $x ; done'

notifications:
  recipients:
    - danhgn@gmail.com
  email:
    on_success: change
    on_failure: always
